/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DriverLicense;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.List;
import javax.smartcardio.ResponseAPDU;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.filechooser.FileNameExtensionFilter;
import utils.EncodeUtils;
import utils.LicenseUtils;

public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        disconnectBtn.setVisible(false);
        faultListView.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        disconnectBtn = new javax.swing.JButton();
        connectBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        updatePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        checkFaultBtn = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        rewriteLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        cardIdText = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        fullNameText = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        birthDateText = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        addressText = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        cardTypeText = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        expireDateText = new javax.swing.JLabel();
        faultPanel = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        faultListView = new javax.swing.JTextArea();
        jPanel34 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        faultComboBox = new javax.swing.JComboBox<>();
        faultDateText = new javax.swing.JFormattedTextField();
        writeFault = new javax.swing.JButton();
        rewritePanel = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        cardIdTextField1 = new javax.swing.JFormattedTextField();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        cardIdTextField = new javax.swing.JFormattedTextField();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        fullNameTextField = new javax.swing.JTextField();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        birthDateTextField = new javax.swing.JFormattedTextField();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        addressTextField = new javax.swing.JTextField();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        expireDateTextField = new javax.swing.JFormattedTextField();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        faultComboBox1 = new javax.swing.JComboBox<>();
        jPanel64 = new javax.swing.JPanel();
        btnChangeExpireDate1 = new javax.swing.JButton();
        jPanel65 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("License Suite");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(774, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 70));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 25, 15));
        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 15));

        disconnectBtn.setText("Disconnect");
        disconnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectBtnActionPerformed(evt);
            }
        });
        jPanel4.add(disconnectBtn);

        connectBtn.setText("Connect");
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });
        jPanel4.add(connectBtn);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(774, 50));

        updatePanel.setBackground(new java.awt.Color(54, 236, 130));
        updatePanel.setPreferredSize(new java.awt.Dimension(190, 50));
        updatePanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Thông tin thẻ");
        jLabel12.setAlignmentX(0.5F);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        updatePanel.add(jLabel12);

        jPanel7.add(updatePanel);

        jPanel13.setBackground(new java.awt.Color(255, 206, 48));
        jPanel13.setPreferredSize(new java.awt.Dimension(190, 50));
        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        checkFaultBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkFaultBtn.setText("Danh sách lỗi");
        checkFaultBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkFaultBtnMousePressed(evt);
            }
        });
        jPanel13.add(checkFaultBtn);

        jPanel7.add(jPanel13);

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));
        jPanel12.setPreferredSize(new java.awt.Dimension(190, 50));
        jPanel12.setLayout(new java.awt.GridLayout(1, 1, 15, 0));

        rewriteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rewriteLabel.setText("Cập nhật thông tin");
        rewriteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rewriteLabelMousePressed(evt);
            }
        });
        jPanel12.add(rewriteLabel);

        jPanel7.add(jPanel12);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setPreferredSize(new java.awt.Dimension(200, 309));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel30);

        jButton1.setText("Đổi ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        jPanel2.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel31.setLayout(new java.awt.CardLayout(1, 1));

        infoPanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        jPanel18.add(jLabel2);

        jPanel14.add(jPanel18, java.awt.BorderLayout.LINE_START);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        cardIdText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel19.add(cardIdText);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên");
        jPanel20.add(jLabel4);

        jPanel15.add(jPanel20, java.awt.BorderLayout.LINE_START);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fullNameText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel21.add(fullNameText);

        jPanel15.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh");
        jPanel22.add(jLabel6);

        jPanel16.add(jPanel22, java.awt.BorderLayout.LINE_START);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        birthDateText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel23.add(birthDateText);

        jPanel16.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ");
        jPanel24.add(jLabel8);

        jPanel17.add(jPanel24, java.awt.BorderLayout.LINE_START);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addressText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel25.add(addressText);

        jPanel17.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel17);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Loại bằng");
        jPanel27.add(jLabel10);

        jPanel26.add(jPanel27, java.awt.BorderLayout.LINE_START);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cardTypeText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel28.add(cardTypeText);

        jPanel26.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel26);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel37.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Ngày hết hạn");
        jPanel37.add(jLabel11);

        jPanel32.add(jPanel37, java.awt.BorderLayout.LINE_START);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        expireDateText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel38.add(expireDateText);

        jPanel32.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel32);

        infoPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel31.add(infoPanel, "card2");

        faultPanel.setBackground(new java.awt.Color(255, 255, 255));
        faultPanel.setLayout(new java.awt.BorderLayout());

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setPreferredSize(new java.awt.Dimension(574, 50));

        jLabel15.setText("Danh sách 5 lỗi vi phạm gần đây");
        jPanel35.add(jLabel15);

        jPanel33.add(jPanel35, java.awt.BorderLayout.PAGE_START);

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setLayout(new java.awt.GridLayout(1, 0));

        faultListView.setColumns(20);
        faultListView.setRows(5);
        jScrollPane1.setViewportView(faultListView);

        jPanel36.add(jScrollPane1);

        jPanel33.add(jPanel36, java.awt.BorderLayout.CENTER);

        faultPanel.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setPreferredSize(new java.awt.Dimension(574, 100));
        jPanel34.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 5, 30));

        jLabel16.setText("Ghi lỗi:");
        jPanel34.add(jLabel16);

        faultComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        faultComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không đội mũ bảo hiểm", "Vượt đèn đỏ", "Vượt quá tải trọng quy định", "Đi sai làn đường", "Uống rượu bia khi tham gia giao thông", "Vượt quá tốc độ" }));
        faultComboBox.setPreferredSize(new java.awt.Dimension(200, 32));
        faultComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faultComboBoxActionPerformed(evt);
            }
        });
        jPanel34.add(faultComboBox);

        try {
            faultDateText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        faultDateText.setPreferredSize(new java.awt.Dimension(178, 32));
        faultDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faultDateTextActionPerformed(evt);
            }
        });
        jPanel34.add(faultDateText);

        writeFault.setText("GHI");
        writeFault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeFaultActionPerformed(evt);
            }
        });
        jPanel34.add(writeFault);

        faultPanel.add(jPanel34, java.awt.BorderLayout.SOUTH);

        jPanel31.add(faultPanel, "card2");

        rewritePanel.setLayout(new java.awt.BorderLayout());

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setLayout(new javax.swing.BoxLayout(jPanel42, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel55.setBackground(new java.awt.Color(255, 255, 255));
        jPanel55.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel55.setLayout(new java.awt.BorderLayout());

        jPanel56.setBackground(new java.awt.Color(255, 255, 255));
        jPanel56.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel56.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel56.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Mã PIN");
        jPanel56.add(jLabel13);

        jPanel55.add(jPanel56, java.awt.BorderLayout.LINE_START);

        jPanel57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel57.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        try {
            cardIdTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cardIdTextField1.setPreferredSize(new java.awt.Dimension(350, 35));
        cardIdTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardIdTextField1ActionPerformed(evt);
            }
        });
        jPanel57.add(cardIdTextField1);

        jPanel55.add(jPanel57, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel55);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel44.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Số thẻ");
        jPanel44.add(jLabel3);

        jPanel43.add(jPanel44, java.awt.BorderLayout.LINE_START);

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        try {
            cardIdTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cardIdTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        cardIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardIdTextFieldActionPerformed(evt);
            }
        });
        jPanel45.add(cardIdTextField);

        jPanel43.add(jPanel45, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel43);

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel47.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel47.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Họ tên");
        jPanel47.add(jLabel5);

        jPanel46.add(jPanel47, java.awt.BorderLayout.LINE_START);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        fullNameTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel48.add(fullNameTextField);

        jPanel46.add(jPanel48, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel46);

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel49.setLayout(new java.awt.BorderLayout());

        jPanel50.setBackground(new java.awt.Color(255, 255, 255));
        jPanel50.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel50.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel50.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh");
        jPanel50.add(jLabel7);

        jPanel49.add(jPanel50, java.awt.BorderLayout.LINE_START);

        jPanel51.setBackground(new java.awt.Color(255, 255, 255));
        jPanel51.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        try {
            birthDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        birthDateTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        birthDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthDateTextFieldActionPerformed(evt);
            }
        });
        jPanel51.add(birthDateTextField);

        jPanel49.add(jPanel51, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel49);

        jPanel52.setBackground(new java.awt.Color(255, 255, 255));
        jPanel52.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel52.setLayout(new java.awt.BorderLayout());

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel53.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel53.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Địa chỉ");
        jPanel53.add(jLabel9);

        jPanel52.add(jPanel53, java.awt.BorderLayout.LINE_START);

        jPanel54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel54.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        addressTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel54.add(addressTextField);

        jPanel52.add(jPanel54, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel52);

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel58.setLayout(new java.awt.BorderLayout());

        jPanel59.setBackground(new java.awt.Color(255, 255, 255));
        jPanel59.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel59.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel59.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Ngày hết hạn");
        jPanel59.add(jLabel17);

        jPanel58.add(jPanel59, java.awt.BorderLayout.LINE_START);

        jPanel60.setBackground(new java.awt.Color(255, 255, 255));
        jPanel60.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        try {
            expireDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        expireDateTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        expireDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireDateTextFieldActionPerformed(evt);
            }
        });
        jPanel60.add(expireDateTextField);

        jPanel58.add(jPanel60, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel58);

        jPanel61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel61.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel61.setLayout(new java.awt.BorderLayout());

        jPanel62.setBackground(new java.awt.Color(255, 255, 255));
        jPanel62.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel62.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel62.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Loại bằng");
        jPanel62.add(jLabel18);

        jPanel61.add(jPanel62, java.awt.BorderLayout.LINE_START);

        jPanel63.setBackground(new java.awt.Color(255, 255, 255));
        jPanel63.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));

        faultComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        faultComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A1", "A2", "A3", "B1", "B2" }));
        faultComboBox1.setPreferredSize(new java.awt.Dimension(350, 32));
        faultComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faultComboBox1ActionPerformed(evt);
            }
        });
        jPanel63.add(faultComboBox1);

        jPanel61.add(jPanel63, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel61);

        jPanel64.setBackground(new java.awt.Color(255, 255, 255));
        jPanel64.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel64.setPreferredSize(new java.awt.Dimension(120, 309));
        jPanel64.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnChangeExpireDate1.setText("Lưu lại");
        btnChangeExpireDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeExpireDate1ActionPerformed(evt);
            }
        });
        jPanel64.add(btnChangeExpireDate1);

        jPanel42.add(jPanel64);

        jPanel65.setBackground(new java.awt.Color(255, 255, 255));
        jPanel65.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 1));
        jPanel42.add(jPanel65);

        rewritePanel.add(jPanel42, java.awt.BorderLayout.CENTER);

        jPanel31.add(rewritePanel, "card2");

        jPanel2.add(jPanel31, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void faultDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faultDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faultDateTextActionPerformed

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed

        // TODO add your handling code here:
        if (APDU.getInstanse().connectCard(EncodeUtils.hexStringToByteArray(Applet.APPLET_AID))) {
            connectBtn.setVisible(false);
            disconnectBtn.setVisible(true);
            UserInfo license = Service.getInstanse().getLicenseInfo(APDU.getInstanse().makeCommand(00, Applet.INS_GET_USER_INFO, 00, 00));
            renderLicenseInfo(license);
            ResponseAPDU response = APDU.getInstanse().makeCommand(00, Applet.INS_GET_AVATAR_IMAGE, 00, 00);
            if (response.getSW1() == 0x90) {
                byte[] buffer = response.getBytes();
                StringBuilder imagePath = new StringBuilder();
                for (int i = 0; i < (buffer.length - 2) ; i++) {
                    imagePath.append(Character.toString((char) buffer[i]));
                }
                jPanel10.removeAll();
                JLabel label = new JLabel(new ImageIcon(imagePath.toString()));
                Component add = jPanel10.add(label);
                jPanel10.revalidate();
                jPanel10.repaint();
            }
            
        }


    }//GEN-LAST:event_connectBtnActionPerformed

    private void checkFaultBtnMousePressed(java.awt.event.MouseEvent evt) {                                               
        // TODO add your handling code here:
        try {
            List<Violation> faultList = Service.getInstanse().getViolationList(APDU.getInstanse().makeCommand(00, Applet.INS_GET_LIST_VIOLATION, 00, 00));
            renderViolationList(faultList);
            infoPanel.setVisible(false);
            faultPanel.setVisible(true);
            rewritePanel.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                          
    
    private void rewriteLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rewriteLabelMousePressed
        // TODO add your handling code here:
        infoPanel.setVisible(false);
        faultPanel.setVisible(false);
        rewritePanel.setVisible(true);
    }//GEN-LAST:event_rewriteLabelMousePressed

    private void disconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectBtnActionPerformed
        // TODO add your handling code here:
        if (APDU.getInstanse().disconnect()) {
            connectBtn.setVisible(true);
            disconnectBtn.setVisible(false);
            clearRecentInfo();
        }
    }//GEN-LAST:event_disconnectBtnActionPerformed

    private void faultComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faultComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faultComboBoxActionPerformed

    private void writeFaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeFaultActionPerformed
        // TODO add your handling code here:
        try {
            JPanel pinPanel = new JPanel();
            JLabel pinLabel = new JLabel("Xác nhận mã pin:");
            JPasswordField pinInput = new JPasswordField(10);
            pinPanel.add(pinLabel);
            pinPanel.add(pinInput);
            String[] options = new String[]{"Huỷ", "OK"};
            int option = JOptionPane.showOptionDialog(null, pinPanel, "Nhập mã pin",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,null, options, options[1]);
            if(option != 1){
                return;
            }
            char[] pinChar = pinInput.getPassword();
            String pin = new String(pinChar);

            if (pin.length() != 4) {
                JOptionPane.showMessageDialog(null, "Mã PIN sai");
                return;
            }
            String tempPin[] = pin.split("");
            byte[] cdataPin = new byte[tempPin.length];
            int j = 0;
            for (String x : tempPin) {
                cdataPin[j++] = (byte) Integer.parseInt(x);
            }
            ResponseAPDU responsePin = APDU.getInstanse().makeCommand(00, Applet.INS_VERIFY_PIN, 00, 00, cdataPin);
            if (responsePin.getSW1() == 0x90) {
                JOptionPane.showMessageDialog(null, "Mã PIN sai");
                return;
            }
            int faultIndex = faultComboBox.getSelectedIndex();
            int faultCode = mapIndexToViolationCode(faultIndex);
            String faultDate = this.faultDateText.getText();
            String splitedDate[] = faultDate.split("/");
            int date = Integer.parseInt(splitedDate[0]);
            int month = Integer.parseInt(splitedDate[1]);
            int yearX = Integer.parseInt(splitedDate[2].charAt(0) + "" + splitedDate[2].charAt(1));
            int yearY = Integer.parseInt(splitedDate[2].charAt(2) + "" + splitedDate[2].charAt(3));
            byte[] cdata = new byte[]{(byte) faultCode, (byte) date, (byte) month, (byte) yearX, (byte) yearY};

            ResponseAPDU response = APDU.getInstanse().makeCommand(00, Applet.INS_INSERT_VIOLATION, 00, 00, cdata);
            if (response.getSW1() == 0x90) {
                JOptionPane.showMessageDialog(null, "Ghi lỗi thành công ");
                List<Violation> faultList = Service.getInstanse().getViolationList(APDU.getInstanse().makeCommand(00, Applet.INS_GET_LIST_VIOLATION, 00, 00));
                renderViolationList(faultList);
            } else {
                JOptionPane.showMessageDialog(null, "Ghi lỗi không thành công");
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_writeFaultActionPerformed

    private void birthDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDateTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.toString();
        ResponseAPDU response = APDU.getInstanse().makeCommand(00, Applet.INS_SET_AVATAR_IMAGE, 00, 00, path.getBytes());
        if (response.getSW1() == 0x90) {
            jPanel10.removeAll();
            JLabel label = new JLabel(new ImageIcon(path));
            Component add = jPanel10.add(label);
            jPanel10.revalidate();
            jPanel10.repaint();
            JOptionPane.showMessageDialog(null, "Ghi thành công ");
        } else {
            JOptionPane.showMessageDialog(null, "Ghi không thành công");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cardIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardIdTextFieldActionPerformed

    private void expireDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expireDateTextFieldActionPerformed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        infoPanel.setVisible(true);
        faultPanel.setVisible(false);
        rewritePanel.setVisible(false);
        UserInfo license = Service.getInstanse().getLicenseInfo(APDU.getInstanse().makeCommand(00, Applet.INS_GET_USER_INFO, 00, 00));
        renderLicenseInfo(license);
    }//GEN-LAST:event_jLabel12MousePressed

    private void btnChangeExpireDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeExpireDate1ActionPerformed
        // TODO add your handling code here:
          String pin = cardIdTextField1.getText();
        if (pin.length() != 4) {
            JOptionPane.showMessageDialog(null, "Mã PIN phải đủ 4 chữ số");
            return;
        }
        String tempPin[] = pin.split("");
        byte[] cdataPin = new byte[tempPin.length];
        int j = 0;
        for (String x : tempPin) {
            cdataPin[j++] = (byte) Integer.parseInt(x);
        }
        ResponseAPDU responsePin = APDU.getInstanse().makeCommand(00, Applet.INS_INIT_PIN, 00, 00, cdataPin);
        if (responsePin.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi mã PIN không thành công ");
            return;
        }
        
        String cardId = cardIdTextField.getText();
        if (cardId.length() != 8) {
            JOptionPane.showMessageDialog(null, "Mã thẻ phải đủ 8 chữ số");
            return;
        }
        String temp[] = cardId.split("");
        byte[] cdataCardId = new byte[temp.length];
        int i = 0;
        for (String x : temp) {
            cdataCardId[i++] = (byte) Integer.parseInt(x);
        }
        ResponseAPDU responseId = APDU.getInstanse().makeCommand(00, Applet.INS_SET_CARD_ID, 00, 00, cdataCardId);
        if (responseId.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi ID không thành công ");
        }
        
        String fullName = fullNameTextField.getText();
        ResponseAPDU responseName = APDU.getInstanse().makeCommand(00, Applet.INS_SET_FULLNAME, 00, 00, fullName.getBytes());
        if (responseName.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi họ tên không thành công ");
        }
        
        String dob = birthDateTextField.getText();
        String splitedDate[] = dob.split("/");
        int date = Integer.parseInt(splitedDate[0]);
        int month = Integer.parseInt(splitedDate[1]);
        int yearX = Integer.parseInt(splitedDate[2].charAt(0) + "" + splitedDate[2].charAt(1));
        int yearY = Integer.parseInt(splitedDate[2].charAt(2) + "" + splitedDate[2].charAt(3));
        byte[] cdataDob = new byte[]{(byte) date, (byte) month, (byte) yearX, (byte) yearY};
        ResponseAPDU responseDob = APDU.getInstanse().makeCommand(00, Applet.INS_SET_BIRTH_DATE, 00, 00, cdataDob);
        if (responseDob.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi ngày sinh không thành công ");
        }
        
        String address = addressTextField.getText();
        ResponseAPDU responseAddress = APDU.getInstanse().makeCommand(00, Applet.INS_SET_ADDRESS, 00, 00, address.getBytes());
        if (responseAddress.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi địa chỉ không thành công ");
        }
        
        String dateInput = expireDateTextField.getText();
        String splitedDateExpired[] = dateInput.split("/");
        int dateExpired = Integer.parseInt(splitedDateExpired[0]);
        int monthExpired = Integer.parseInt(splitedDateExpired[1]);
        int yearXExpired = Integer.parseInt(splitedDateExpired[2].charAt(0) + "" + splitedDateExpired[2].charAt(1));
        int yearYExpired = Integer.parseInt(splitedDateExpired[2].charAt(2) + "" + splitedDateExpired[2].charAt(3));
        byte[] cdataExpiredDate = new byte[]{(byte) dateExpired, (byte) monthExpired, (byte) yearXExpired, (byte) yearYExpired};
        ResponseAPDU responseExpiredDate = APDU.getInstanse().makeCommand(00, Applet.INS_SET_EXPIRE_DATE, 00, 00, cdataExpiredDate);
        if (responseExpiredDate.getSW1() != 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi ngày hết hạn không thành công ");
        }
        int typeIndex = faultComboBox1.getSelectedIndex();
        int typeCode = mapIndexToDriverType(typeIndex);
        ResponseAPDU responseType = APDU.getInstanse().makeCommand(00, Applet.INS_SET_CARD_TYPE, (byte)typeCode, 00);
        if (responseType.getSW1() == 0x90) {
            JOptionPane.showMessageDialog(null, "Ghi thành công ");
        } else {
            JOptionPane.showMessageDialog(null, "Ghi loại bằng không thành công");
        }
    }//GEN-LAST:event_btnChangeExpireDate1ActionPerformed

    private void faultComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faultComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faultComboBox1ActionPerformed

    private void cardIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardIdTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressText;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel birthDateText;
    private javax.swing.JFormattedTextField birthDateTextField;
    private javax.swing.JButton btnChangeExpireDate1;
    private javax.swing.JLabel cardIdText;
    private javax.swing.JFormattedTextField cardIdTextField;
    private javax.swing.JFormattedTextField cardIdTextField1;
    private javax.swing.JLabel cardTypeText;
    private javax.swing.JLabel checkFaultBtn;
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton disconnectBtn;
    private javax.swing.JLabel expireDateText;
    private javax.swing.JFormattedTextField expireDateTextField;
    private javax.swing.JComboBox<String> faultComboBox;
    private javax.swing.JComboBox<String> faultComboBox1;
    private javax.swing.JFormattedTextField faultDateText;
    private javax.swing.JTextArea faultListView;
    private javax.swing.JPanel faultPanel;
    private javax.swing.JLabel fullNameText;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rewriteLabel;
    private javax.swing.JPanel rewritePanel;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JButton writeFault;
    // End of variables declaration//GEN-END:variables
    private void renderLicenseInfo(UserInfo license) {
        cardIdText.setText(license.getCardId());
        fullNameText.setText(license.getFullName());
        addressText.setText(license.getAddress());
        birthDateText.setText(license.getBirthDate());
        expireDateText.setText(license.getExpireDate());
        cardTypeText.setText(license.getCardType());
    }

    private void clearRecentInfo() {
        cardIdText.setText("");
        fullNameText.setText("");
        addressText.setText("");
        birthDateText.setText("");
        expireDateText.setText("");
        cardTypeText.setText("");
        jPanel10.removeAll();
        jPanel10.repaint();
    }

    private int mapIndexToViolationCode(int faultIndex) {
        switch (faultIndex) {
            case 0:
                return Violation.MISSING_EQUIPMENT_FAULT;
            case 1:
                return Violation.LIGHT_SIGNAL_FAULT;
            case 2:
                return Violation.OVER_WEIGHT_FAULT;
            case 3:
                return Violation.WRONG_LANE_FAULT;
            case 4:
                return Violation.VIOLATE_ALCOHOL_FAULT;
            case 5:
                return Violation.OVER_SPEED_FAULT;
            default:
                return 0;
        }
    }
    
    private int mapIndexToDriverType(int typeIndex) {
        switch(typeIndex) {
            case 0:
                return LicenseUtils.CARD_TYPE_A1;
            case 1:
                return LicenseUtils.CARD_TYPE_A2;
            case 2:
                return LicenseUtils.CARD_TYPE_A3;
            case 3:
                return LicenseUtils.CARD_TYPE_B1;
            case 4:
                return LicenseUtils.CARD_TYPE_B2;
            default: 
                return 0;
        }
    }

    private void renderViolationList(List<Violation> faultList) {
        faultListView.setText("");
        faultList.forEach((fault) -> {
            faultListView.append(fault.toString() + "\n\n");
        });
    }

}
